name: embed_ime
description: The basic component of the Mongolian embed IME.
version: 0.0.2
homepage: https://github.com/Satsrag/embed_input

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: