name: demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mongol: ^8.0.0
    # path: ../../mongol
#    git:
#      url: git@github.com:suragch/mongol.git
  menk_embed_ime_db: #^0.0.1
    path: ../menk_embed_ime_db
  zcode_embed_ime_db: #^0.0.2
    path: ../zcode_embed_ime_db
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: MenkQagan
      fonts:
        - asset: fonts/MQG8F02.ttf
    - family: ZcodeQagan
      fonts:
        - asset: fonts/z52tsagaantig.ttf
